spring:
 security:
        oauth2:
            client:
                registration:
                    uridentity-dev:
                        client-id: web_app
                        client-name: web_app
                        #client-secret: 9faa4aaa-39fe-43bc-8d4f-ec17292df641
                        client-secret: b5222343-3c60-438f-bf79-d1220d460cbe
                        provider: uridentity-dev
                        authorization-grant-type: authorization_code
                        scope: openid, profile
                        redirect-uri: "https://uridentity-dev.myidentity.net/login/oauth2/code/{registrationId}"
                   # preview:
                    #    client-id: web_app
                     #   client-name: web_app
                        #client-secret: 9faa4aaa-39fe-43bc-8d4f-ec17292df641
                      #  client-secret: afd430a6-9610-474b-8a9c-70a6d527ff68
                       # provider: preview
                       # authorization-grant-type: authorization_code
                       # scope: openid, profile
                       # redirect-uri: "https://preview.myidentity.net/login/oauth2/code/{registrationId}"
                   # ine:
                    #    client-id: web_app
                     #   client-name: web_app
                     #   client-secret: 82e55edf-41bb-413f-a0e9-327bab994b28
                     #   provider: ine
                     #   authorization-grant-type: authorization_code
                     #   scope: openid, profile
                     #   redirect-uri: "https://ine.epicidentity.net/login/oauth2/code/{registrationId}"
                   # demo:
                   #     client-id: web_app
                   #     client-name: web_app
                   #     client-secret: 11b88f6e-0fc2-42cd-abad-9bcc5807371b
                   #     #client-secret: 811a46cb-ddec-401f-9721-2e44f4e41f74
                   #     provider: demo
                   #     authorization-grant-type: authorization_code
                   #     scope: openid, profile
                   #     redirect-uri: "https://demo.epicidentity.net/login/oauth2/code/{registrationId}"
                   # idemia:
                   #     client-id: web_app
                   #     client-name: web_app
                   #     client-secret: bcf89e88-d416-4468-ba2b-e2061620c44b
                   #     #client-secret: 811a46cb-ddec-401f-9721-2e44f4e41f74
                   #     provider: idemia
                   #     authorization-grant-type: authorization_code
                   #     scope: openid, profile
                   #     redirect-uri: "https://idemia.epicidentity.net/login/oauth2/code/{registrationId}"
                    meidmts-dev:
                        client-id: web_app
                        client-name: web_app
                        client-secret: 9a2c6c0b-fdb6-4fcd-a6cb-ebcb19963ab8
                        provider: meidmts-dev
                        authorization-grant-type: authorization_code
                        scope: openid, profile
                        redirect-uri: "https://meidmts-dev.myidentity.net/login/oauth2/code/{registrationId}"
                   # incadence:
                   #     client-id: web_app
                   #     client-name: web_app
                   #     client-secret: ff6fac64-de3e-4441-9679-a0aecd79a31f
                   #     provider: incadence
                   #     authorization-grant-type: authorization_code
                   #     scope: openid, profile
                   #     redirect-uri: "https://incadence.epicidentity.net/login/oauth2/code/{registrationId}"
                provider:
                    uridentity-dev:
                        authorization-uri: ${kc.realm1-url}/protocol/openid-connect/auth
                        issuer-uri: ${kc.realm1-url}
                        jwk-set-uri: ${kc.realm1-url}/protocol/openid-connect/certs
                        token-uri: ${kc.realm1-url}/protocol/openid-connect/token
                        user-name-attribute: preferred_username
                    #ine:
                    #    authorization-uri: ${kc.realm2-url}/protocol/openid-connect/auth
                    #    issuer-uri: ${kc.realm2-url}
                    #    jwk-set-uri: ${kc.realm2-url}/protocol/openid-connect/certs
                    #    token-uri: ${kc.realm2-url}/protocol/openid-connect/token
                    #    user-name-attribute: preferred_username
                    #demo:
                    #    authorization-uri: ${kc.realm3-url}/protocol/openid-connect/auth
                    #    issuer-uri: ${kc.realm3-url}
                    #    jwk-set-uri: ${kc.realm3-url}/protocol/openid-connect/certs
                    #    token-uri: ${kc.realm3-url}/protocol/openid-connect/token
                    #    user-name-attribute: preferred_username
                    #preview:
                    #    authorization-uri: ${kc.realm4-url}/protocol/openid-connect/auth
                    #    issuer-uri: ${kc.realm4-url}
                    #    jwk-set-uri: ${kc.realm4-url}/protocol/openid-connect/certs
                    #    token-uri: ${kc.realm4-url}/protocol/openid-connect/token
                    #    user-name-attribute: preferred_username
                    #idemia:
                    #    authorization-uri: ${kc.realm5-url}/protocol/openid-connect/auth
                    #    issuer-uri: ${kc.realm5-url}
                    #    jwk-set-uri: ${kc.realm5-url}/protocol/openid-connect/certs
                    #    token-uri: ${kc.realm5-url}/protocol/openid-connect/token
                    #    user-name-attribute: preferred_username
                    meidmts-dev:
                         authorization-uri: ${kc.realm6-url}/protocol/openid-connect/auth
                         issuer-uri: ${kc.realm6-url}
                         jwk-set-uri: ${kc.realm6-url}/protocol/openid-connect/certs
                         token-uri: ${kc.realm6-url}/protocol/openid-connect/token
                         user-name-attribute: preferred_username
                    #incadence:
                    #    authorization-uri: ${kc.realm7-url}/protocol/openid-connect/auth
                    #    issuer-uri: ${kc.realm7-url}
                    #    jwk-set-uri: ${kc.realm7-url}/protocol/openid-connect/certs
                    #    token-uri: ${kc.realm7-url}/protocol/openid-connect/token
                    #    user-name-attribute: preferred_username						
kc:
    base-url: https://iam-dev.myidentity.net:8443/auth
    realm1: uridentity-dev
    realm2: ine
    realm3: demo
    realm4: preview
    realm5: idemia
    realm6: meidmts-dev
    realm7: incadence
    realm1-url: ${kc.base-url}/realms/${kc.realm1}
    realm2-url: ${kc.base-url}/realms/${kc.realm2}
    realm3-url: ${kc.base-url}/realms/${kc.realm3}
    realm4-url: ${kc.base-url}/realms/${kc.realm4}
    realm5-url: ${kc.base-url}/realms/${kc.realm5}
    realm6-url: ${kc.base-url}/realms/${kc.realm6}
    realm7-url: ${kc.base-url}/realms/${kc.realm7}
