version: '3'
services:
   ca:
    image: myidentity/myidentity_images:ca_latest_${branch}
    container_name: ca
    environment:
        - SPRING_PROFILES_ACTIVE=dev,swagger
        - SPRING_CLOUD_CONSUL_HOST=consul
        - SPRING_CLOUD_CONSUL_PORT=8500
        - SPRING_DATASOURCE_URL=jdbc:mariadb://database-dev.myidentity.net:3306/ca
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=trust@myadmin123
        - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
        - 10002:10002
