version: '3'
services:
  apigateway:
    image: myidentity/myidentity_images:apigateway_latest_${branch}
    container_name: apigateway
    environment:
        - SPRING_PROFILES_ACTIVE=dev,swagger
        - SPRING_CLOUD_CONSUL_HOST=consul
        - SPRING_CLOUD_CONSUL_PORT=8500
        - SPRING_CLOUD_CONFIG_URI=http://configserver-dev.myidentity.net
        - SPRING_CLOUD_CONFIG_ENABLED=true
        - SPRING_CLOUD_CONFIG_FAILFAST=true
        - SPRING_DATASOURCE_URL=jdbc:mariadb://database-dev.myidentity.net:3306/gateway
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=trust@myadmin123
        - ZUUL_ROUTES_CASERVICE_URL=http://ca:10002
        - ZUUL_ROUTES_USERMANAGEMENT_URL=http://usermanagement:10003
        - ZUUL_ROUTES_APDU_URL=http://apdu:10004
        - ZUUL_ROUTES_BIOMETRICVERIFICATION_URL=http://biometricverification:10006
        - ZUUL_ROUTES_REPORTSMANAGEMENT_URL=http://reportsmanagement:10010
        - JHIPSTER_SLEEP=30 # gives time for the database to boot before the application
    ports:
        - 10007:10007
