version: '3'
services:
  midb:
    image: mariadb:10.1.17
    container_name: midb
    volumes:
      - /midb:/var/lib/mysql
      - ../data/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=trust@myadmin123
    ports:
      - 3306:3306
