version: '3'
services:
  biometricverification:
    image: uridentity/uridentity_images:biometricverification_latest
    container_name: biometricverification
    environment:
        - SPRING_PROFILES_ACTIVE=dev,swagger
        - SPRING_CLOUD_CONSUL_HOST=consul
        - SPRING_CLOUD_CONSUL_PORT=8500
        - AWS_ACCESS_KEY=AKIA3ZKUS6LM3EAOQ3CJ
        - AWS_SECRET_KEY=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
        - SPRING_DATASOURCE_URL=jdbc:mariadb://database-dev.myidentity.net:3306/biometricverification
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=trust@myadmin123
        - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        - LD_LIBRARY_PATH=/opt/neuro/linux/
    ports:
        - 10006:10006
    volumes:
#        - /var/lib/docker/volumes/data-volume/
         - /opt/neuro/linux:/opt/neuro/linux/
