version: '3'
services:
  gateway:
    image: uridentity/uridentity_images:gateway_latest
    container_name: gateway
    environment:
        - SPRING_PROFILES_ACTIVE=dev,swagger
        - SPRING_CLOUD_CONSUL_HOST=consul
        - SPRING_CLOUD_CONSUL_PORT=8500
        - SPRING_CLOUD_CONFIG_URI=http://configserver-dev.myidentity.net
        - SPRING_DATASOURCE_URL=jdbc:mariadb://database-dev.myidentity.net:3306/gateway
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=trust@myadmin123
        - APPLICATION_USERMANAGEMENT_HOST=usermanagement
        - APPLICATION_USERMANAGEMENT_PORT=10003
        - ZUUL_ROUTES_CASERVICE_URL=http://ca:10002
        - ZUUL_ROUTES_USERMANAGEMENT_URL=http://usermanagement:10003
        - ZUUL_ROUTES_APDU_URL=http://apdu:10004
        - ZUUL_ROUTES_BIOMETRICVERIFICATION_URL=http://biometricverification:10006
        - ZUUL_ROUTES_REPORTSMANAGEMENT_URL=http://reportsmanagement:10010
        - JHIPSTER_SLEEP=30 # gives time for the database to boot before the application
 #       - SPRING_ZIPKIN_BASE_URL=http://35.171.82.245:9411/
        - SPRING_SLEUTH_SAMPLER_PERCENTAGE=1.0
#        - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
    ports:
        - 10001:10001
